### ISSUE TITLE
toForeground not working

### ISSUE THREAD

**Issue by hdering** [arteck/ioBroker.fullybrowser#178]
Hello,
I would like to start an app (Doorbird) via the Fully Kiosk Browser and display FKB again after a while. Starting the app works, but FKB doesn't show up again. I tried to use the toForeground command, but nothing happens. However, the command ScreenOff/ScreenOn works.
At the top of the status bar I also see that FKB is running.
Does anyone have an idea how I can get FKB back in the foreground?

**Comment by arteck** [comment]
so check 3.0.8 Version

**Comment by hdering** [comment]
@arteck 
I tested it with version 3.0.8. Unfortunately it doesn't work yet.

I see the following error in iobroker:
`<html>
<body>

at RestApiFully.axiosSendCmd (/opt/iobroker/node_modules/iobroker.fullybrowser/lib/restApi.js:86:28)
--
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async RestApiFully.sendCmd (/opt/iobroker/node_modules/iobroker.fullybrowser/lib/restApi.js:49:28)
at async fullybrowserControll.onStateChange (/opt/iobroker/node_modules/iobroker.fullybrowser/main.js:281:37)
2023-12-07 17:54:10.032 - error: fullybrowser.0 (3159736) [REST] 192.168.188.230: Sending command toForeground failed: Error: TypeError: Cannot use 'in' operator to search for 'status' in


</body>
</html>`

**Comment by arteck** [comment]
Fixed in new version

**Comment by hdering** [comment]
Error message no longer appears with version 3.0.9, FKB is still not in the foreground.
